### ISSUE TITLE
Please solve  asap

### ISSUE THREAD

**Issue by python-hmv** [johann-lr/discord-stats#6]
/home/container/messageHandler.js:33
                                        const users = element.users.map(x => x.id);
                                                                    ^
TypeError: element.users.map is not a function
    at ReactionCollector.<anonymous> (/home/container/messageHandler.js:33:34)
    at ReactionCollector.emit (node:events:539:35)
    at ReactionCollector.handleCollect (/home/container/node_modules/discord.js/src/structures/interfaces/Collector.js:100:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by johann-lr** [comment]
Hi, the discord api changed a lot during the last 3-4 years (since this project was created). I didn't actually maintain it over that time. Feel free to create a pull request as I won't regularly care :)
